### ISSUE TITLE
How to get URLs from Artstation

### ISSUE THREAD

**Issue by eveningglow** [onion-liu/aahq-dataset#5]
Thanks for your great work! I think this dataset contributes a lot to the machine learning community and is also useful to me. I am wondering how you collected URLs from a specific channel (e.g., portraits) in Artstation. Can you share your code?

**Comment by onion-liu** [comment]
Thanks for your attention!
I found the channel id of a specific channel from 
https://www.artstation.com/api/v2/search/projects/filter_fields.json
and
https://github.com/AndriyMykhash/ArtStation-tg-Python-bot/blob/master/bot_configs.json

and used this query to get the artwork info
```
'https://www.artstation.com/api/v2/community/channels/projects.json?channel_id={}&page={}&sorting={}&dimension=all&per_page=100'
```
For example,
```
https://www.artstation.com/api/v2/community/channels/projects.json?channel_id=113&page=1&sorting=trending&dimension=all&per_page=100
```
will return 100 artwork links from the `Portraits` (channel_id=113) channel.

It is worth noting that this method can only get up to 10000 artworks because the numbers of `page` and `per_page` are all up to 100. So I also used [gallery-dl](https://github.com/mikf/gallery-dl) to crawl images with the `portraits` keyword.

I hope this answer will help you.

**Comment by eveningglow** [comment]
Thank you for your help! I tried using gallery-dl, but I could not crawl images with the specific keyword (e.g., portraits). The command I use is `gallery-dl "https://www.artstation.com/search?sort_by=relevance&query=portrait"`, but the downloaded images are not portraits. Can you help me with this problem?

**Comment by onion-liu** [comment]
> Thank you for your help! I tried using gallery-dl, but I could not crawl images with the specific keyword (e.g., portraits). The command I use is `gallery-dl "https://www.artstation.com/search?sort_by=relevance&query=portrait"`, but the downloaded images are not portraits. Can you help me with this problem?

@eveningglow The command ```gallery-dl "https://www.artstation.com/search?sort_by=relevance&query=portrait"``` works for me!

There may be some images that are not portraits because the pages of the search results may contain intermediate results in the author's painting process. Please check more downloaded images.

Some downloaded images: 
<img width="677" alt="tmp" src="https://user-images.githubusercontent.com/6346064/192769295-f4f34e15-9f07-4b14-a9b2-0b8fcaabf479.png">

**Comment by onion-liu** [comment]
Close for now, feel free to reopen it if you have any further questions.
